version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.4.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: 
          name: Install Dependencies
          command: yarn install
      - run: 
          name: Compile Contracts
          command: yarn run build
      - run: 
          name: Lint Contracts
          command: yarn run lint
      - run: 
          name: Test Migrations
          command: yarn run migrate
      - run: 
          name: Test Contracts
          command: yarn run test
