version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.3.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: 
          name: Install Dependencies
          command: make install
      - run: 
          name: Compile Contracts
          command: make build
      - run: 
          name: Lint Contracts
          command: make lint
      - run: 
          name: Test Migrations
          command: make migrate
      - run: 
          name: Test Contracts
          command: make test
